name: 'Blockera Packages Manager'
description: 'The Blockera Github Action to management packages.'
author: 'blockerabot'
inputs:
  TOKEN:
    description: 'The Personal Access Token for authentication'
    required: true
  USERNAME:
    description: 'The username of bot account'
    required: true
  PASSWORD:
    description: 'The password of bot account'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'

permissions:
  contents: write
  pull-requests: write
