name: 'Blockera Packages Manager'
description: 'The Blockera Github Action to management packages.'
author: 'blockerabot'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token for authentication'
    required: true
  BLOCKERABOT_PAT:
    description: 'Personal access token for Blockerabot'
    required: true

runs:
  using: 'node16'
  main: 'src/main.js'

permissions:
  contents: write
  pull-requests: write