name: 'Blockera Packages Manager'
description: 'The Blockera Github Action to management packages.'
author: 'blockerabot'
branding:
  icon: package
  color: blue
inputs:
  TOKEN:
    description: 'The Personal Access Token for authentication'
    required: true
  USERNAME:
    description: 'The username of bot account'
    required: true
  EMAIL:
    description: 'The email address of bot account'
    required: true
  BASE_BRANCH:
    description: 'The base branch to sync changes into (default: master)'
    required: false
    default: 'master'
  CREATE_SYNC_BRANCH:
    description: 'Whether to create a new sync branch (true) or commit directly to base branch (false)'
    required: false
    default: 'true'

runs:
  using: 'node20'
  main: 'dist/index.js'

permissions:
  contents: write
  pull-requests: write
